### ISSUE TITLE
Failure with Gradle 6

### ISSUE THREAD

**Issue by tueda** [xvik/gradle-quality-plugin#17] opened 2019-11-09 21:14 UTC
The plugin does not work with Gradle 6.0. An example is here (which works well without upgrading Gradle to 6.0):
```
git clone https://github.com/tueda/test-gradle-quality-plugin.git
cd test-gradle-quality-plugin
./gradlew wrapper --gradle-version=6.0
./gradlew
```
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'test-gradle-quality-plugin'.
> Failed to notify project evaluation listener.
   > org/gradle/api/plugins/quality/FindBugsPlugin
```

Probably, this is because of the old version of the SpotBugs plugin, which is incompatible with Gradle 6, e.g., spotbugs/spotbugs-gradle-plugin#95.

**Comment by xvik** [comment] 2019-11-10 07:21
Thank you for the info! 
The root cause is finbugs plugin, removed in gradle 6.
I will remove findbugs support too.  The new version should be released in a few days.

**Closed** 2019-11-10 12:29 UTC

**Comment by eekboom** [comment] 2019-11-15 09:16
Would love to see a release soon, so that we can proceed with update to gradle 6.

Thanks a lot for your work!

**Comment by xvik** [comment] 2019-11-15 09:18
I will release it today or tomorrow

**Comment by xvik** [comment] 2019-11-16 10:57
[released](https://github.com/xvik/gradle-quality-plugin/releases/tag/4.0.0)

**Comment by eekboom** [comment] 2019-11-22 11:24
Thanks a lot for the quick fix!
