### ISSUE TITLE
Failure Spotbugs with gradle 5.0 - GC overhead limit exceeded

### ISSUE THREAD

**Issue by dovogt** [xvik/gradle-quality-plugin#12] opened 2019-02-08 09:40 UTC
The execution of spotbugs will fail if gradle <5.0 is used.
Worker memory was reduced to 5.0 gradle. In the Spotbugs plugin you can increase the heap with the help of the parameter jvmargs. Is this also about this plugin?

https://discuss.gradle.org/t/spotbugsplugin-with-gradle-5-0-fails-gc-overhead-limit-exceeded/30461/4
https://github.com/spotbugs/spotbugs-gradle-plugin/issues/85

**Comment by xvik** [comment] 2019-02-16 18:18
Please try [new version](https://github.com/xvik/gradle-quality-plugin/releases/tag/3.4.0): it sets default heap size for spotbugs tasks to 1g (which was the implicit default in gradle 4).

I will close this issue, but I will better check gradle 5 compatibility and, most likely, there will be another release addressing full gradle 5 compatibility (and future version will require gradle 5 due to gradle api changes).

**Comment by dovogt** [comment] 2019-02-19 15:16
Thank you for your quick help. Spotbugs works now, unfortunately pmd does not work anymore and brings the error: GC overhead limit exceeded

In the gradle.properties I tried to set the property to org.gradle.jvmargs = -Xms1g. Then spotbbugs will work again, but pmd and jacoco will not work anymore.

**Comment by xvik** [comment] 2019-02-20 06:13
I'll try to look at this. I did not port my own projects to gradle 5 yet (except gradle plugins) because they ruin BOM's support (at least this requires close investigation), so did not face all this myself. Hope to find some time for migration soon.

If you know related issues for this pmd/jacoco problem please post links here (I did the last fix barely on suggestions from the linked issues).

**Comment by dovogt** [comment] 2019-02-20 10:37
I have now downgraded the wrapper to 4.10.2. Version 3.4.0 of the quality-plugin also causes the error "GC overhead limit exceeded"
If I switch back to version 3.3.0 it will work again.

**Comment by xvik** [comment] 2019-02-20 11:32
Most likeley your build is affected by newer pmd version (but I don't see any bug reports about memory problems related to newer pmd versions). 
First, try to increase memory: `org.gradle.jvmargs=-Xmx2g` (this should be enough)

If it will not help then you can search for "problematic" pmd version:
Quality plugin versions (3.4.0 and 3.3.0) should differ only in used quality tool versions. So version 3.4.0 with configuration:
```
quality{
  checkstyleVersion = '8.14'
  pmdVersion='6.9.0'
  spotbugsVersion='3.1.9'
}
```
Is essentially the same as 3.3.0 (and should work)

Check 3.4.0 with older plugin versions (config above) to make sure plugin itself works. And after that try to increase pmd version (6.10.0, 6.11.0) to find exactly which pmd version cause problem. If it's not pmd version, then try upgrading spotbugs (until 3.1.11) and checkstyle (until 8.17) (maybe issue  caused by a combination of new tools).

I don't know how to reproduce such issue (my projects work without problems) so can't suggest anything better than increasing available momory. Pmd task did not fork jvm so it should help.

**Comment by dovogt** [comment] 2019-02-21 07:06
I have only changed the quality plugin version. The versions for the tools I have always deposited firmly in the build.gradle.  However, I have two very large projects with many classes

```
	// Tools versions
	checkstyleVersion = '8.16'
	spotbugsVersion = '3.1.10'
	pmdVersion = '6.10.0'
```

**Comment by xvik** [comment] 2019-02-21 08:05
Are they open sourced? Because right now I can't reproduce the issue and so, unfortunately,  can't help much.

**Comment by dovogt** [comment] 2019-02-25 15:55
Hello,
the software is not open source and I cannot make the project publicly available.  I could provide you with a build scan.

**Comment by xvik** [comment] 2019-02-25 17:09
Yes, please. Maybe it will help (I doubt, but maybe :) )

**Comment by dovogt** [comment] 2019-02-28 08:14
Hello,
below you will find the links for the two buildscan results. Both were executed with Gradle 4.10.2.

Command:
gradlew spotBugsMain --scan --no-daemon

4.10.2 mit 3.3.0:
https://scans.gradle.com/s/b2meoc4ngib7m

4.10.2 mit 3.4.0:
https://scans.gradle.com/s/zfy7x2u3v3xqo

**Comment by xvik** [comment] 2019-03-04 01:37
Mmm I was wrong: spotbugs use gradle workers api and so there was no restriction on memory before (actually 1/4 of physical memory), so 1g, currenly set by quality plugin 3.4.0, is less then it was before. The only way now to fix it is to increase memory setting manually:
```
tasks.withType(SpotBugsTask) {
    maxHeapSize = '2g' // or even 3
}
```

In the nest version I will add this setting directly into the extension (for simplicity):
```
quality {
     spotbugsMaxHeapSize = '2g'
}
```

**Closed** 2019-03-04 02:02 UTC
